#!/usr/bin/env bash

_bem_autocomplete() {
	local cur cmd link name names commands

	cur=${COMP_WORDS[COMP_CWORD]}
	cmd=${COMP_WORDS[1]}

	commands='init install remove rm list ls status uninstall-bem version help'

	if ((COMP_CWORD == 1)); then
		COMPREPLY=($(compgen -W "$commands" -- "$cur"))
		return
	fi

	case $cmd in
		install)
			case ${COMP_WORDS[COMP_CWORD-1]} in
				-n)
					COMPREPLY=()
					;;
				*)
					COMPREPLY=($(compgen -f -- "$cur"))
					;;
			esac
			;;

		remove|rm|status)
			names=

			for link in "$HOME/.bem/bin"/*; do
				[[ -L $link ]] || continue

				name=${link##*/}
				[[ $name == bem ]] && continue

				names+="$name "
			done

			COMPREPLY=($(compgen -W "$names" -- "$cur"))
			;;

		help)
			COMPREPLY=($(compgen -W "$commands" -- "$cur"))
			;;

		*)
			COMPREPLY=()
			;;
	esac
}

complete -F _bem_autocomplete bem
