#!/usr/bin/env bash

help(){
    printf "ansicolor\t\tprint all the 256 ansi color codes\nansicolor -b\t\tprint all the 256 ansi color codes (background colored output)\nansicolor <n>\t\t(0 <= n <= 255) print some strings in the n ansi color\nansicolor -b <n>\t(0 <= n <= 255) print some strings in the n ansi color (background colored output)\n"
}

ansicolors() {
    local i
    printf "\nStandard:\t"
    for i in {0..7}; do
        printf "\x1b[$COLOR_TYPE;5;${i}m   %d  " "$i"
    done
    printf "\033[0;10m\n\nIntense:\t"
    for i in {8..9}; do
        printf "\x1b[$COLOR_TYPE;5;${i}m   %d  " "$i"
    done
    for i in {10..15}; do
        printf "\x1b[$COLOR_TYPE;5;${i}m  %d  " "$i"
    done
    printf "\033[0;10m\n\n\n\t\t"
    local j
    for i in {0..9}; do
        for j in {0..7}; do
            printf "\x1b[$COLOR_TYPE;5;$(($i * 8 + $j + 16))m  %d  " "$(($i * 8 + $j + 16))"
        done
        printf "\033[0;10m\n\t\t"
    done
    for i in {96..99}; do
        printf "\x1b[$COLOR_TYPE;5;${i}m  %d  " "$i"
    done;
    for i in {100..103}; do
        printf "\x1b[$COLOR_TYPE;5;${i}m %d  " "$i"
    done;
    printf "\033[0;10m\n\t\t"
    for i in {11..26}; do
        for j in {0..7}; do
            printf "\x1b[$COLOR_TYPE;5;$(($i * 8 + $j + 16))m %d  " "$(($i * 8 + $j + 16))"
        done
        printf "\033[0;10m\n\t\t"
    done
    printf "\n\nGreys:\t\t"
    for i in {232..255}; do
        printf "\x1b[$COLOR_TYPE;5;${i}m%d  " "$i"
    done
    printf "\033[0;10m\n\n"
}

COLOR_TYPE=38

if [[ -z $1 ]]; then
    ansicolors
else
    if [[ $1 = "-b" ]]; then
        COLOR_TYPE=48
        shift
    fi
    if [[ -z $1 ]]; then
        ansicolors
    elif [[ "$1" =~ ^[0-9]+$ ]] && (( $1 >= 0 && $1 <= 255 )); then
        for i in {0..10}; do
            printf "\x1b[${i};$COLOR_TYPE;5;${1}m"
            echo -n "\\x1b[$i;$COLOR_TYPE;5;${1}m"
            printf "\033[0;10m\n"
        done
    else
        help
    fi

fi